/*
 * Angus Henry
 * frommarks.java
 * This program accepts different marks and then provides important information about the marks 
 * 22/05/2018
 */

package U3A6_Marks;
import java.util.*;
/**
 *
 * @author anhen3335
 */
public class formmarks extends javax.swing.JFrame {
// Here we are declaring or Array for the marks, our sorted marks array,  our maximun mark and out minimum mark.
ArrayList <Integer> marks = new ArrayList();
ArrayList <String> markssort = new ArrayList();
int max;
int min =101;
    /**
     * Creates new form formmarks
     */
    public formmarks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        buttonSort = new javax.swing.JButton();
        buttonAnalyze = new javax.swing.JButton();
        labelStudentMark = new javax.swing.JLabel();
        textEnterMarks = new javax.swing.JTextField();
        buttonAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMarksSort = new javax.swing.JTextArea();
        labelAverage = new javax.swing.JLabel();
        labelMax = new javax.swing.JLabel();
        labelMin = new javax.swing.JLabel();
        labelRange = new javax.swing.JLabel();
        labelfour = new javax.swing.JLabel();
        labelThree = new javax.swing.JLabel();
        labelTwo = new javax.swing.JLabel();
        labelOne = new javax.swing.JLabel();
        labelR = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        labelTitle.setText("Marks Prgram");

        buttonSort.setText("Sort");
        buttonSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSortActionPerformed(evt);
            }
        });

        buttonAnalyze.setText("Analyze");
        buttonAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnalyzeActionPerformed(evt);
            }
        });

        labelStudentMark.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelStudentMark.setText("Student Marks:");

        textEnterMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnterMarksActionPerformed(evt);
            }
        });
        textEnterMarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textEnterMarksKeyPressed(evt);
            }
        });

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        textMarksSort.setEditable(false);
        textMarksSort.setColumns(20);
        textMarksSort.setRows(5);
        jScrollPane1.setViewportView(textMarksSort);

        labelAverage.setText("Average Mark:");

        labelMax.setText("Maximum:");

        labelMin.setText("Minimum:");

        labelRange.setText("Range: ");

        labelfour.setText("Level 4:");

        labelThree.setText("Level 3: ");

        labelTwo.setText("Level 2:");

        labelOne.setText("Level 1:");

        labelR.setText("Level R:");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelR, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelThree, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelfour, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelOne, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAnalyze)
                                    .addComponent(labelAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRange, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(labelStudentMark, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textEnterMarks, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                                .addGap(69, 69, 69)
                                .addComponent(buttonAdd))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(buttonSort))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textEnterMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonAdd))
                    .addComponent(labelStudentMark, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(labelAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelRange, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelfour)
                        .addGap(18, 18, 18)
                        .addComponent(labelThree)
                        .addGap(18, 18, 18)
                        .addComponent(labelTwo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSort)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelR)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAnalyze)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  /**
 *
 * This button sorts all of the marks from lowest to highest
 */
    private void buttonSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSortActionPerformed
    Collections.sort (markssort);
        textMarksSort.setText ("");
        for (int i = 0; i < markssort.size(); i++){
            textMarksSort.append (markssort.get (i));
            textMarksSort.append ("\n");
           System.out.println (markssort);
           
        }
    }//GEN-LAST:event_buttonSortActionPerformed

    private void textEnterMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnterMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnterMarksActionPerformed

    private void textEnterMarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEnterMarksKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnterMarksKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//close program       
        System.exit (0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
  /**
 *
 * this adds the marks to the array and what the maximum and minimum value is
 */
    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
       // collects the number that will be tested
        int testnum = Integer.parseInt(textEnterMarks.getText ());
       if (testnum >=0 && testnum <= 100) {
           markssort.add (textEnterMarks.getText());
        marks.add (Integer.parseInt(textEnterMarks.getText ()));
         labelError.setText ("");      
     // Call the the Max and Min methods    
    Max();
    Min();
         // blanks the error message if one is there
         textMarksSort.append (textEnterMarks.getText());
         textMarksSort.append ("\n");
       }
       else{
         // For when a nomuber ist not between 0 and 100
           labelError.setText ("That is not valid");
       }
       System.out.println (marks);
       System.out.println (markssort);
       //System.out.println (max);
       //System.out.println (min);
    }//GEN-LAST:event_buttonAddActionPerformed
 /**
 *
 * Calculates Max
 */
    private void Max (){
int testnum = Integer.parseInt(textEnterMarks.getText ());
     if (testnum > max){
           max = testnum;        }   
 }
    /**
 *
 * Calculates min
 */
 private void Min () {
    int testnum = Integer.parseInt(textEnterMarks.getText ());
     if (testnum < min){
             min = testnum;
         }
 }
    /**
 *
 * This find all th information needed about the marks such and calculates how many of each level there is
 */
    private void buttonAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnalyzeActionPerformed
       Double average;
    average = AverageFind();
    int range = Rangefind(max, min);
    int four = 0;
    int three = 0;
    int two = 0;
    int one = 0;
    int R = 0;
        for (int i = 0; i < marks.size(); i++){
       if (marks.get(i) >= 80){
           four ++;
       }
       else if (marks.get(i) >= 70 && marks.get(i)< 80){
        three ++;   
       }
       else if (marks.get(i) >= 60 && marks.get(i)< 70){
        two ++;   
       }
       else if (marks.get(i) >= 50 && marks.get(i)< 60){
        one ++;   
       }
       else {
           R ++;
       }
       
       }
        average = average / marks.size();
        labelAverage.setText ("Average Mark: " + average + "%");
       	labelMax.setText ("Maximum: " + max);
        labelMin.setText ("Minimum: " + min);
        labelRange.setText ("Range: "+ range);
        labelfour.setText ("Level 4: "+ four);
        labelThree.setText ("Level 3: "+ three);
        labelTwo.setText ("Level 2: "+ two);
        labelOne.setText ("Level 1: "+ one);
        labelR.setText ("Level R: "+ R);
    }//GEN-LAST:event_buttonAnalyzeActionPerformed
  /**
 *
 * This determines the range between the highest and the lowest mark
 */
    private int Rangefind(int max, int min){
        return (max - min); 
    }
    /**
 *
 * This calculates the average of all the marks
 */
    private double AverageFind (){
        double average = 0.0;
        for (int i = 0; i < marks.size(); i++){
       average += marks.get (i);
        }
        return (average);
    }
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formmarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formmarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formmarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formmarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formmarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonAnalyze;
    private javax.swing.JButton buttonSort;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAverage;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelMax;
    private javax.swing.JLabel labelMin;
    private javax.swing.JLabel labelOne;
    private javax.swing.JLabel labelR;
    private javax.swing.JLabel labelRange;
    private javax.swing.JLabel labelStudentMark;
    private javax.swing.JLabel labelThree;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTwo;
    private javax.swing.JLabel labelfour;
    private javax.swing.JTextField textEnterMarks;
    private javax.swing.JTextArea textMarksSort;
    // End of variables declaration//GEN-END:variables
}